services:
  - type: web
    name: ipa-upload-bot
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        sync: false
      - key: RELEASE_TAG_PREFIX
        value: build-
      - key: HEALTH_PORT
        value: "10000"
      - key: TELEGRAM_API_BASE
        # URL của Local Bot API Server (dịch vụ Render khác của bạn)
        value: "https://<your-local-bot-api>.onrender.com"
