services:
  - type: web
    name: ipa-github-uploader
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        sync: false
      - key: TELEGRAM_API_BASE
        value: "https://telegram-bot-api-server-jsy3.onrender.com"
      - key: RELEASE_TAG_PREFIX
        value: "build-"
      - key: HEALTH_PORT
        value: "10000"
