services:
  - type: web
    name: ipa-upload-bot
    env: docker
    rootDir: bot-uploader
    dockerfilePath: ./bot-uploader/Dockerfile
    plan: free
    autoDeploy: true

    envVars:
      - key: BOT_API_BASE
        value: https://telegram-bot-api-server-jsy3.onrender.com
      - key: BOT_TOKEN
        sync: false       # ðŸ”’ nháº­p thá»§ cÃ´ng trÃªn Render Dashboard
      - key: GITHUB_TOKEN
        sync: false       # ðŸ”’ nháº­p thá»§ cÃ´ng trÃªn Render Dashboard
      - key: GITHUB_REPO
        value: trinhtruongphong-bot/ipa-storage
      - key: RELEASE_TAG_PREFIX
        value: uploads
      - key: PORT
        value: 10000
